# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab2(self):
    self.driver.get("https://demo.opencart.com/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    self.driver.find_element(By.LINK_TEXT, "PC (0)").click()
    self.driver.find_element(By.LINK_TEXT, "Continue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show > .fa-caret-down").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("abc@gmail.com")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".mb-3:nth-child(4) > .col-form-label")
    assert len(elements) > 0
  
