# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDay16Q1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_day16Q1(self):
    self.driver.get("https://tutorialsninja.com/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.LINK_TEXT, "https://tutorialsninja.com/demo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown .hidden-xs").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "input-firstname").send_keys("Gollavilli")
    self.driver.find_element(By.NAME, "lastname").send_keys("Thanmayi")
    self.driver.find_element(By.CSS_SELECTOR, "#input-email").send_keys("thanmayigollavilli@gmail.com")
    self.driver.find_element(By.XPATH, "//input[@id=\'input-telephone\']").send_keys("6302223005")
    self.driver.find_element(By.XPATH, "//div[@id=\'content\']/form/fieldset[2]/div/div/input").send_keys("Thanmayi@1234")
    self.driver.find_element(By.XPATH, "//fieldset[2]/div[2]/div/input").send_keys("Thanmayi@123")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "fieldset:nth-child(3) .col-sm-2")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".radio-inline:nth-child(2)").click()
    self.driver.find_element(By.NAME, "agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("gollavillithanmayi@gmail.com")
    self.driver.find_element(By.ID, "input-confirm").click()
    self.driver.find_element(By.ID, "input-confirm").click()
    self.driver.find_element(By.ID, "input-confirm").click()
    self.driver.find_element(By.ID, "input-confirm").send_keys("Thanmayi@1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown .hidden-xs").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("gollavillithanmayi@gmail.com")
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("Thanmayi@1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h2:nth-child(1)")
    assert len(elements) > 0
  
